dist: trusty
language: rust
services: docker
sudo: required

rust: nightly

env: TARGET=x86_64-unknown-linux-gnu
matrix:
  include:
    - env: TARGET=thumbv7em-none-eabihf

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - auto
    - try

notifications:
  email:
    on_success: never
